### ISSUE TITLE
EnvoyFilter VIRTUAL_HOST REMOVE patch operation will destroy other route configuration

### ISSUE THREAD

**Issue by bboshiZ** [bboshiZ/mail#4]
apply this envoyfilter to istio
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: to-global-sidecar
  namespace: sample
spec:
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      routeConfiguration:
        name: "5000"
        vhost:
          name: allow_any
    patch:
      operation: REMOVE
  - applyTo: ROUTE_CONFIGURATION
    match:
      routeConfiguration:
        name: "5000"
    patch:
      operation: MERGE
      value:
        virtual_hosts:
        - domains:
          - '*'
          name: to_global_sidecar
          routes:
          - match:
              prefix: /
            route:
              cluster: outbound|5000||global-sidecar.sample.svc.cluster.local

```

then  in sample ns, istio-proxy logs.
this will result the EnvoyFilter not work and some other RouteConfiguration config error.
envoy logs report  RouteConfigurationValidationError.VirtualHosts[4] (virtual_hosts {domains: "*"}) lost the "name" field
```
2021-12-03T08:57:30.820859Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[4]: embedded message failed validation | caused by VirtualHostValidationError.Name: value length must be at least 1 characters): name: "80"
virtual_hosts {
  name: "istio-egressgateway.istio-system.svc.cluster.local:80"
  domains: "istio-egressgateway.istio-system.svc.cluster.local"
  domains: "istio-egressgateway.istio-system.svc.cluster.local:80"
  domains: "istio-egressgateway.istio-system"
  domains: "istio-egressgateway.istio-system:80"
  domains: "istio-egressgateway.istio-system.svc"
  domains: "istio-egressgateway.istio-system.svc:80"
  domains: "10.247.209.206"
  domains: "10.247.209.206:80"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "outbound|80||istio-egressgateway.istio-system.svc.cluster.local"
      timeout {
      }
      max_stream_duration {
        max_stream_duration {
        }
        grpc_timeout_header_max {
        }
      }
    }
    decorator {
      operation: "istio-egressgateway.istio-system.svc.cluster.local:80/*"
    }
    name: "default"
  }
  include_request_attempt_count: true
}
virtual_hosts {
  name: "lazyload.istio-system.svc.cluster.local:80"
  domains: "lazyload.istio-system.svc.cluster.local"
  domains: "lazyload.istio-system.svc.cluster.local:80"
  domains: "lazyload.istio-system"
  domains: "lazyload.istio-system:80"
  domains: "lazyload.istio-system.svc"
  domains: "lazyload.istio-system.svc:80"
  domains: "10.247.108.156"
  domains: "10.247.108.156:80"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "outbound|80||lazyload.istio-system.svc.cluster.local"
      timeout {
      }
      max_stream_duration {
        max_stream_duration {
        }
        grpc_timeout_header_max {
        }
      }
    }
    decorator {
      operation: "lazyload.istio-system.svc.cluster.local:80/*"
    }
    name: "default"
  }
  include_request_attempt_count: true
}
virtual_hosts {
  name: "sleep.istio-system.svc.cluster.local:80"
  domains: "sleep.istio-system.svc.cluster.local"
  domains: "sleep.istio-system.svc.cluster.local:80"
  domains: "sleep.istio-system"
  domains: "sleep.istio-system:80"
  domains: "sleep.istio-system.svc"
  domains: "sleep.istio-system.svc:80"
  domains: "10.247.226.215"
  domains: "10.247.226.215:80"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "outbound|80||sleep.istio-system.svc.cluster.local"
      timeout {
      }
      max_stream_duration {
        max_stream_duration {
        }
        grpc_timeout_header_max {
        }
      }
    }
    decorator {
      operation: "sleep.istio-system.svc.cluster.local:80/*"
    }
    name: "default"
  }
  include_request_attempt_count: true
}
virtual_hosts {
  name: "tracing.istio-system.svc.cluster.local:80"
  domains: "tracing.istio-system.svc.cluster.local"
  domains: "tracing.istio-system.svc.cluster.local:80"
  domains: "tracing.istio-system"
  domains: "tracing.istio-system:80"
  domains: "tracing.istio-system.svc"
  domains: "tracing.istio-system.svc:80"
  domains: "10.247.89.135"
  domains: "10.247.89.135:80"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "outbound|80||tracing.istio-system.svc.cluster.local"
      timeout {
      }
      max_stream_duration {
        max_stream_duration {
        }
        grpc_timeout_header_max {
        }
      }
    }
    decorator {
      operation: "tracing.istio-system.svc.cluster.local:80/*"
    }
    name: "default"
  }
  include_request_attempt_count: true
}
virtual_hosts {
  domains: "*"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "PassthroughCluster"
      timeout {
      }
      max_grpc_timeout {
      }
    }
    name: "allow_any"
  }
  include_request_attempt_count: true
}
validate_clusters {
}
```
